const List<String> stationNames = [
  "Abbadia Lariana",
  "Abbiate Guazzone",
  "Abbiategrasso",
  "Acquanegra Cremonese",
  "Airolo",
  "Airuno",
  "Albairate",
  "Albano S.Alessandro",
  "Albate-Trecallo",
  "Albizzate Solbiate Arno",
  "Albonese",
  "Albuzzano",
  "Alessandria",
  "Ambivere Mapello",
  "Andora",
  "Anzano Del Parco",
  "Arcene",
  "Arcisate",
  "Arcore",
  "Ardenno Masino",
  "Arena Po",
  "Arenzano",
  "Arona",
  "Arosio",
  "Arquata Scrivia",
  "Asola",
  "Asso",
  "Bagnolo Mella",
  "Balerna",
  "Barasso-Comerio",
  "Barbianello",
  "Baveno",
  "Belgioioso",
  "Belgirate",
  "Bellano Tartavalle Terme",
  "Bellinzona",
  "Bergamo",
  "Bergamo Ospedale",
  "Besana",
  "Besnate",
  "Besozzo",
  "Bianzone",
  "Biasca",
  "Biassono-Lesmo Parco",
  "Bisuschio Viggiu'",
  "Boario Terme",
  "Bollate Centro",
  "Bollate Nord",
  "Bolzano",
  "Borgo Lavezzaro",
  "Borgolombardo",
  "Borgonato-Adro",
  "Bornato-Calino",
  "Bovisio Masciago",
  "Bozzolo",
  "Brenna-Alzate",
  "Breno",
  "Brescia",
  "Brescia Borgo San Giovanni",
  "Brescia Violino",
  "Bressana Argine",
  "Bressana Bottarone",
  "Broni",
  "Busseto",
  "Busto Arsizio",
  "Busto Arsizio Nord",
  "Buttafava",
  "Cabiate",
  "Cadenazzo",
  "Cadorago",
  "Calde'",
  "Calolziocorte Olginate",
  "Calusco",
  "Calvisano",
  "Camnago-Lentate",
  "Camogli S.Fruttuoso",
  "Canegrate",
  "Canneto Sull'Oglio",
  "Cantello Gaggiolo",
  "Cantu'",
  "Cantu'-Cermenate",
  "Canzo",
  "Capo Di Ponte",
  "Capolago-Riva S.Vitale",
  "Capralba",
  "Carate-Calo'",
  "Caravaggio",
  "Carimate",
  "Carnate Usmate",
  "Caronno Pertusella",
  "Carugo-Giussano",
  "Casalbuttano",
  "Casaletto Vaprio",
  "Casalmaggiore",
  "Casalpusterlengo",
  "Casletto-Rogeno",
  "Caslino Al Piano",
  "Caslino D'Erba",
  "Casorate Sempione",
  "Cassago-Nibionno-Bulciago",
  "Cassano D'Adda",
  "Castano Primo",
  "Casteggio",
  "Castegnato",
  "Castel D'Ario",
  "Castel S.Giovanni",
  "Castellanza",
  "Castelleone",
  "Castellucchio",
  "Castelnuovo Del Garda",
  "Castelvetro",
  "Castione Andevenno",
  "Castione-Arbedo",
  "Castronno",
  "Cava Carbonara",
  "Cava Tigozzi",
  "Cavaria Oggiona Ierago",
  "Cazzago S. Martino",
  "Cedegolo",
  "Ceriano Laghetto Groane",
  "Ceriano Laghetto-Solaro",
  "Cernusco-Merate",
  "Certosa Di Pavia",
  "Cesano Boscone",
  "Cesano Maderno",
  "Cesate",
  "Ceto-Cerveno",
  "Chiari",
  "Chiasso",
  "Chiavari",
  "Chiavenna",
  "Chignolo Po",
  "Chiuduno",
  "Chiuro",
  "Cisano Caprino Bergamasco",
  "Cislago",
  "Cittiglio",
  "Civate",
  "Cividate-Calcio",
  "Cividate-Malegno",
  "Coccaglio",
  "Cocquio Trevisago",
  "Codogno",
  "Cogno-Esine",
  "Colico",
  "Colmegna",
  "Cologne",
  "Colorno",
  "Como Borghi",
  "Como Camerlata",
  "Como Lago",
  "Como S.Giovanni",
  "Corbetta S.Stefano",
  "Cormano-Cusano Milanino",
  "Corsico",
  "Corteolona",
  "Cosio Traona",
  "Costa Masnaga",
  "Crema",
  "Cremona",
  "Cucciago",
  "Cuzzago",
  "Darfo-Corna",
  "Delebio",
  "Dervio",
  "Desenzano Del Garda-Sirmione",
  "Desio",
  "Diano",
  "Domodossola",
  "Dorio",
  "Dormelletto",
  "Dubino",
  "Edolo",
  "Erba",
  "Ferno-Lonate Pozzolo",
  "Ferrera Lomellina",
  "Fidenza",
  "Finale Ligure Marina",
  "Fino Mornasco",
  "Fiumelatte",
  "Gaggiano",
  "Gallarate",
  "Galliate",
  "Galliate Parco Del Ticino",
  "Gambolo'-Remondo'",
  "Garbagna",
  "Garbagnate Milanese",
  "Garbagnate Parco Delle Groane",
  "Garlasco",
  "Gavirate",
  "Gavirate Verbano",
  "Gazzada Schianno Morazzone",
  "Gazzo Pieve S.Giacomo",
  "Gemonio",
  "Genova Brignole",
  "Genova Piazza Principe",
  "Gerenzano-Turate",
  "Gerra",
  "Ghedi",
  "Gordola",
  "Grandate-Breccia",
  "Gropello Cairoli",
  "Grumello Del Monte",
  "Imperia",
  "Induno Olona",
  "Inverigo",
  "Iseo",
  "Ispra",
  "La Spezia Centrale",
  "Lambrinia",
  "Lambrugo-Lurago D'Erba",
  "Lamone-Cadempino",
  "Laveno Mombello",
  "Laveno Mombello Lago",
  "Lecco",
  "Lecco Maggianico",
  "Leggiuno Monvalle",
  "Legnano",
  "Lesa",
  "Lesmo",
  "Levanto",
  "Levate",
  "Lierna",
  "Lissone-Muggio'",
  "Loano",
  "Locarno",
  "Locate Triulzi",
  "Locate Varesino-Carbonate",
  "Lodi",
  "Lomazzo",
  "Lomello",
  "Lonato",
  "Lugano",
  "Lugano Paradiso",
  "Luino",
  "Lungavilla",
  "Macherio Sovico",
  "Macherio-Canonica",
  "Madignano",
  "Magadino-Vira",
  "Magenta",
  "Maleo",
  "Malnate",
  "Malonno",
  "Malpensa Aeroporto T1",
  "Malpensa Aeroporto T2",
  "Mandello Del Lario",
  "Manerbio",
  "Mantova",
  "Mantova Frassine",
  "Marcaria",
  "Mariano Comense",
  "Maroggia-Melano",
  "Marone-Zone",
  "Meda",
  "Mede",
  "Meina",
  "Melegnano",
  "Melide",
  "Melzo",
  "Mendrisio",
  "Mendrisio S. Martino",
  "Mergozzo",
  "Merone",
  "Mezzani Rondani",
  "Mezzocorona",
  "Mezzovico",
  "Milano Affori",
  "Milano Bovisa Politecnico",
  "Milano Bruzzano Parco Nord",
  "Milano Cadorna",
  "Milano Centrale",
  "Milano Certosa",
  "Milano Dateo",
  "Milano Domodossola",
  "Milano Forlanini",
  "Milano Greco Pirelli",
  "Milano Lambrate",
  "Milano Lancetti",
  "Milano Porta Garibaldi",
  "Milano Porta Garibaldi Passante",
  "Milano Porta Genova",
  "Milano Porta Romana",
  "Milano Porta Venezia",
  "Milano Porta Vittoria",
  "Milano Quarto Oggiaro",
  "Milano Repubblica",
  "Milano Rogoredo",
  "Milano Romolo",
  "Milano S.Cristoforo",
  "Milano Tibaldi - Bocconi",
  "Milano Villapizzone",
  "Minusio",
  "Miradolo Terme",
  "Moiana",
  "Molteno",
  "Montello Gorlago",
  "Montirone",
  "Monza",
  "Monza Sobborghi",
  "Morbegno",
  "Morengo Bariano",
  "Mornago Cimbro",
  "Morosolo Casciago",
  "Mortara",
  "Motta S.Damiano",
  "Mozzate",
  "Nicorvo",
  "Nogara",
  "Novara",
  "Novara Nord",
  "Novate Milanese",
  "Novate-Mezzola",
  "Novi Ligure",
  "Oggiono",
  "Olcio",
  "Olevano",
  "Olgiate-Calco-Brivio",
  "Olmeneta",
  "Ora",
  "Orio Litta",
  "Osnago",
  "Ospedaletto Lodigiano",
  "Ospitaletto Mantovano",
  "Ospitaletto Travagliato",
  "Paderno Dugnano",
  "Paderno Franciacorta",
  "Paderno Robbiate",
  "Palazzolo Milanese",
  "Palazzolo Sull'Oglio",
  "Palestro",
  "Parabiago",
  "Parma",
  "Parona Lomellina",
  "Passirano",
  "Pavia",
  "Pavia Porta Garibaldi",
  "Pegognaga",
  "Peschiera Del Garda",
  "Piacenza",
  "Piadena",
  "Pian Camuno-Gratacasolo",
  "Pian Di Borno",
  "Pietra Ligure",
  "Pieve Albignola",
  "Pieve Emanuele",
  "Pilzone",
  "Pinarolo Po",
  "Pino-Tronzano",
  "Pioltello Limito",
  "Piona",
  "Pisogne",
  "Pizzighettone",
  "Poggio Rusco",
  "Poggiridenti-Tresivio-Piateda",
  "Ponte D'Adda",
  "Ponte In Valtellina",
  "Ponte S.Marco",
  "Ponte S.Pietro",
  "Pontecurone",
  "Pontelambro-Castelmarte",
  "Pontida",
  "Portichetto-Luisago",
  "Porto Ceresio",
  "Porto Valtravaglia",
  "Pozzolo Formigaro",
  "Pozzuolo Martesana",
  "Prata Camportaccio",
  "Pregnana M.",
  "Premosello Chiovenda",
  "Provaglio-Timoline",
  "Quartino",
  "Quistello",
  "Ranzo-S. Abbondio",
  "Rapallo",
  "Recco",
  "Remedello Sopra",
  "Remedello Sotto",
  "Renate-Veduggio",
  "Rescaldina",
  "Rho",
  "Rho Fiera Milano",
  "Riazzino",
  "Rivera-Bironico",
  "Robbio",
  "Robecco-Pontevico",
  "Romano",
  "Rottofreno",
  "Rovato",
  "Rovato Centro",
  "Rovato Fn",
  "Rovellasca-Manera",
  "Rovello Porro",
  "Rovereto",
  "S.Antonino",
  "S.Benedetto Po",
  "S.Cassiano Valchiavenna",
  "S.Cristina E Bissone",
  "S.Donato Milanese",
  "S.Giacomo Di Teglio",
  "S.Giovanni In Croce",
  "S.Giuletta",
  "S.Giuliano Milanese",
  "S.Margherita Ligure Portofino",
  "S.Martino Cava",
  "S.Michele In Bosco",
  "S.Nazzaro",
  "S.Nicolo'",
  "S.Pietro Berbenno",
  "S.Stefano Lodigiano",
  "S.Zeno Folzano",
  "S.Zenone Al Lambro",
  "Sairano",
  "Sairano Zinasco",
  "Sala Al Barro-Galbiate",
  "Sale Marasino",
  "Samolaco",
  "Sangiano",
  "Sannazzaro",
  "Sarmato",
  "Saronno",
  "Saronno Sud",
  "Sartirana",
  "Savona",
  "Schivenoglia",
  "Secugnago",
  "Segrate",
  "Seregno",
  "Seriate",
  "Serravalle Scrivia",
  "Sesto Calende",
  "Sesto S.Giovanni",
  "Sestri Levante",
  "Seveso",
  "Seveso Baruccana",
  "Somma Lombardo",
  "Sondrio",
  "Sonico",
  "Soresina",
  "Spotorno Noli",
  "Stabio",
  "Stezzano",
  "Stradella",
  "Stresa",
  "Sulzano",
  "Suzzara",
  "Taino Angera",
  "Talamona",
  "Tavazzano",
  "Taverne-Torricella",
  "Tenero",
  "Ternate Varano Borghi",
  "Terno",
  "Tirano",
  "Toline",
  "Torre De' Picenardi",
  "Torreberetti",
  "Torrile S.Polo",
  "Tortona",
  "Tradate",
  "Travedona Biandronno",
  "Trecate",
  "Trecella",
  "Trento",
  "Tresenda-Aprica-Teglio",
  "Treviglio",
  "Treviglio Ovest",
  "Trezzano Sul Naviglio",
  "Triuggio-Ponte Albiate",
  "Tromello",
  "Turbigo",
  "Valenza",
  "Valle Lomellina",
  "Valmadonna",
  "Valmadrera",
  "Vanzaghello-Magnago",
  "Vanzago Pogliano",
  "Varazze",
  "Varedo",
  "Varenna Esino",
  "Varese",
  "Varese Casbeno",
  "Varese Nord",
  "Vedano Olona",
  "Vello",
  "Venegono Inferiore",
  "Venegono Superiore-Castiglione O.",
  "Verbania-Pallanza",
  "Verceia",
  "Vercelli",
  "Vercurago S.Girolamo",
  "Verdello Dalmine",
  "Vergiate",
  "Verolanuova",
  "Verona Porta Nuova",
  "Vespolate",
  "Viadana Bresciana",
  "Vidalengo",
  "Vigevano",
  "Vignate",
  "Villa Di Tirano",
  "Villa Raverio",
  "Villamaggiore",
  "Villanova D'Ardenghi",
  "Villasanta",
  "Villetta Malagnino",
  "Visano",
  "Vittuone Arluno",
  "Voghera",
  "Vogogna Ossola",
  "Zinasco Nuovo"
];
