// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***DJEfAZ3PSdNfDJw2Q2hhrguJe56B62uSk',
    appId: '1:161773136206:web:f9688ad6d1016f783b961f',
    messagingSenderId: '161773136206',
    projectId: 'traintribe-f2c7b',
    authDomain: 'traintribe-f2c7b.firebaseapp.com',
    storageBucket: 'traintribe-f2c7b.firebasestorage.app',
    measurementId: 'G-W4T4Y3R2H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***CE3Se1zkJEFKDDGCJetDhszX_gO9LtVCw',
    appId: '1:161773136206:android:831e5298f4ece3f63b961f',
    messagingSenderId: '161773136206',
    projectId: 'traintribe-f2c7b',
    storageBucket: 'traintribe-f2c7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***DAXDYZH0hSbCYWgMNpTSS05TjZoSthHpk',
    appId: '1:161773136206:ios:e2b627155c62a3853b961f',
    messagingSenderId: '161773136206',
    projectId: 'traintribe-f2c7b',
    storageBucket: 'traintribe-f2c7b.firebasestorage.app',
    androidClientId: '161773136206-nk4dmhrc422ilp0bf9jthtvijo7hnlhd.apps.googleusercontent.com',
    iosClientId: '161773136206-c2d8akoc2nem8aa3200sv9b52csg4imr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainTribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***DAXDYZH0hSbCYWgMNpTSS05TjZoSthHpk',
    appId: '1:161773136206:ios:e2b627155c62a3853b961f',
    messagingSenderId: '161773136206',
    projectId: 'traintribe-f2c7b',
    storageBucket: 'traintribe-f2c7b.firebasestorage.app',
    androidClientId: '161773136206-nk4dmhrc422ilp0bf9jthtvijo7hnlhd.apps.googleusercontent.com',
    iosClientId: '161773136206-c2d8akoc2nem8aa3200sv9b52csg4imr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainTribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***DJEfAZ3PSdNfDJw2Q2hhrguJe56B62uSk',
    appId: '1:161773136206:web:73dde46d39d58eff3b961f',
    messagingSenderId: '161773136206',
    projectId: 'traintribe-f2c7b',
    authDomain: 'traintribe-f2c7b.firebaseapp.com',
    storageBucket: 'traintribe-f2c7b.firebasestorage.app',
    measurementId: 'G-TVML6RKSPN',
  );
}
