name: train_tribe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  toggle_switch: ^2.3.0
  go_router: ^14.8.1
  image_picker: ^1.1.2
  intl: any
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  window_size: ^0.1.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
